---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of restaurants with grades A, B, C, for Asian Cuisine

```{r}
data("rest_inspec")

rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))

rest_inspec %>% 
   filter(cuisine_description %in% c("Korean","Chinese", "Asian", "Japanese", "Thai","Indian", "Filipino", "Vietnamese/Cambodian/Malaysia", "Bangladeshi", "Indonesian", "Chinese/Cuban", "Chinese/Japanese")) %>% 
   plot_ly(x = ~cuisine_description,  color= ~grade , colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Grades for different inspection types in restaurants in bronx

```{r}
rest_inspec %>% 
  filter(boro == "Bronx") %>%
  plot_ly(x = ~inspection_type, y = ~score, color = ~grade, type = "scatter", mode = "markers")
```

### Distribution of scores for restaurants in the different Boroughs. 

```{r}
rest_ggplot = 
  rest_inspec %>% 
  ggplot(aes(x = boro, y = score, fill = boro)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(rest_ggplot)

```

