---
title: "Plotly Graphics"
output: 
  html_document:
    toc: true
    toc_float: true
---

## examples of plotly

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

```

```{r}

rest_inspec =
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))
```


```{r}
rest_inspec %>% 
   filter(cuisine_description %in% c("Korean","Chinese", "Asian", "Japanese", "Thai","Indian", "Filipino", "Vietnamese/Cambodian/Malaysia", "Bangladeshi", "Indonesian", "Chinese/Cuban", "Chinese/Japanese")) %>% 
   plot_ly(x = ~cuisine_description,  color= ~grade , colors = "viridis")
```

```{r}
rest_inspec %>% 
  filter(boro == "Bronx") %>%
  plot_ly(x = ~inspection_type, y = ~score, color = ~grade, type = "scatter", mode = "markers")
```

```{r}
rest_ggplot = 
  rest_inspec %>% 
  ggplot(aes(x = boro, y = score, fill = boro)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(rest_ggplot)
```

